FROM node:latest as node

RUN useradd -u 1001 -m kip2
USER kip2

RUN mkdir /home/kip2/src
WORKDIR /home/kip2/src

COPY --chown=kip2:kip2 README.md .
COPY --chown=kip2:kip2 Makefile .
COPY --chown=kip2:kip2 client client

EXPOSE 3000

######

FROM node as react

RUN npm install
ENTRYPOINT make react
